// <auto-generated />
using System;
using CentCom.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CentCom.Common.Migrations.Postgres
{
    [DbContext(typeof(NpgsqlDbContext))]
    [Migration("20200914041044_AddBanAttribute")]
    partial class AddBanAttribute
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CentCom.Common.Models.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("BanAttributes")
                        .HasColumnName("ban_attributes")
                        .HasColumnType("integer");

                    b.Property<string>("BanID")
                        .HasColumnName("ban_id")
                        .HasColumnType("text");

                    b.Property<long>("BanType")
                        .HasColumnName("ban_type")
                        .HasColumnType("bigint");

                    b.Property<string>("BannedBy")
                        .IsRequired()
                        .HasColumnName("banned_by")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime>("BannedOn")
                        .HasColumnName("banned_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CKey")
                        .IsRequired()
                        .HasColumnName("c_key")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("Expires")
                        .HasColumnName("expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .HasColumnName("reason")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnName("source")
                        .HasColumnType("integer");

                    b.Property<string>("UnbannedBy")
                        .HasColumnName("unbanned_by")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id")
                        .HasName("pk_bans");

                    b.HasIndex("CKey")
                        .HasName("ix_bans_c_key");

                    b.HasIndex("Source")
                        .HasName("ix_bans_source");

                    b.ToTable("bans");
                });

            modelBuilder.Entity("CentCom.Common.Models.BanSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Display")
                        .HasColumnName("display")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<long>("RoleplayLevel")
                        .HasColumnName("roleplay_level")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_ban_sources");

                    b.ToTable("ban_sources");
                });

            modelBuilder.Entity("CentCom.Common.Models.FlatBansVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnName("performed_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Version")
                        .HasColumnName("version")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_flat_bans_version");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasName("ix_flat_bans_version_name_version");

                    b.ToTable("flat_bans_version");
                });

            modelBuilder.Entity("CentCom.Common.Models.JobBan", b =>
                {
                    b.Property<int>("BanId")
                        .HasColumnName("ban_id")
                        .HasColumnType("integer");

                    b.Property<string>("Job")
                        .HasColumnName("job")
                        .HasColumnType("text");

                    b.HasKey("BanId", "Job")
                        .HasName("pk_job_bans");

                    b.ToTable("job_bans");
                });

            modelBuilder.Entity("CentCom.Common.Models.Ban", b =>
                {
                    b.HasOne("CentCom.Common.Models.BanSource", "SourceNavigation")
                        .WithMany("Bans")
                        .HasForeignKey("Source")
                        .HasConstraintName("fk_bans_ban_sources_source_navigation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentCom.Common.Models.JobBan", b =>
                {
                    b.HasOne("CentCom.Common.Models.Ban", "BanNavigation")
                        .WithMany("JobBans")
                        .HasForeignKey("BanId")
                        .HasConstraintName("fk_job_bans_bans_ban_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
