<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GitHubActionsTestLogger" Version="3.0.5" />
        <PackageReference Include="MinVer" Version="7.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.63.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CentCom.Common\CentCom.Common.csproj" />
        <ProjectReference Include="..\CentCom.Server\CentCom.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="BanServices\TgBanSample.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
