<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageReference Include="Enums.NET" Version="5.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
        <PackageReference Include="MinVer" Version="7.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
        <PackageReference Include="Remora.Rest" Version="4.0.0" />
    </ItemGroup>

</Project>
