<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <UserSecretsId>c60f1e59-3afa-4470-870a-bbd1ca32cb16</UserSecretsId>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="BlazorLocalTime" Version="2.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="MudBlazor" Version="9.*"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.4" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\CentCom.Common\CentCom.Common.csproj" />
    </ItemGroup>
</Project>