name: ci
on:
  push:
    branches: [master]
  pull_request:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  ci:
    name: ubuntu
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write  # Required to comment on PRs
    steps:
      - name: Set PR number (Linux)
        run: |
          echo "PRNumber=${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"
        if: github.event_name == 'pull_request'
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --configuration Release -- --report-trx --results-directory ./TestResults
      - name: Comment PR with results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ./TestResults/*.trx
          comment_mode: always